// Generated by "npm run codegen". Do not modify this file manually.
import type { BN } from '@project-serum/anchor';
import type { PublicKey } from '@solana/web3.js';

export type CoverState = {
  readonly coverStatePdaBump: number;
  readonly coverMetadataStateKey: PublicKey;
  readonly coverId: BN;
  readonly coverOwner: PublicKey;
  readonly coverReferrer: PublicKey;
  readonly coverProductId: BN;
  readonly coverBeginTimestamp: BN;
  readonly coverEndTimestamp: BN;
  readonly coverCurrency: PublicKey;
  readonly coverAmount: BN;
  readonly coverClaimedAmount: BN;
  readonly coverOccupiedCommonAmount: BN;
  readonly coverOccupiedIndividualAmount: BN;
  readonly coverPremiumCurrency: PublicKey;
  readonly coverPremiumAmount: BN;
  readonly coverPremiumLastDispatchTimetamp: BN;
  readonly coverPremiumLastDispatchTotalAmount: BN;
  readonly coverStatus: BN;
  readonly coverSavedStatus: BN;
};
export type CoverMetadataState = {
  readonly coverAdminAuthKey: PublicKey;
  readonly coverCallerKeyArray: PublicKey[];
  readonly coverPremiumCurrency: PublicKey;
  readonly coverCurrency: PublicKey;
  readonly coverMinAmount: BN;
  readonly coverMaxAmount: BN;
  readonly coverMinDurationInDays: BN;
  readonly coverMaxDurationInDays: BN;
  readonly coverExtendedClaimDurationInDays: BN;
  readonly coverCount: BN;
};
export type InitializeMetadataStateParam = {
  readonly coverPremiumCurrency: PublicKey;
  readonly coverCurrency: PublicKey;
  readonly coverMinAmount: BN;
  readonly coverMaxAmount: BN;
  readonly coverMinDurationInDays: BN;
  readonly coverMaxDurationInDays: BN;
  readonly coverExtendedClaimDurationInDays: BN;
};
export type InitializeMetadataStateAccounts = {
  readonly programInitializerAuth: PublicKey | string;
  readonly programMetadataState: PublicKey | string;
  readonly coverAdminAuth: PublicKey | string;
  readonly sysvarRent: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
export type AdminUpdateCallerInfoParam = {
  readonly callerIndex: BN;
  readonly callerKey: PublicKey;
};
export type AdminUpdateCallerInfoAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly coverAdminAuth: PublicKey | string;
};
export type AdminUpdateAdminAuthInfoAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly newCoverAdminAuth: PublicKey | string;
  readonly coverAdminAuth: PublicKey | string;
  readonly sysvarRent: PublicKey | string;
};
export type AdminUpdateMetadataInfoParam = {
  readonly coverPremiumCurrency: PublicKey;
  readonly coverCurrency: PublicKey;
  readonly coverMinAmount: BN;
  readonly coverMaxAmount: BN;
  readonly coverMinDurationInDays: BN;
  readonly coverMaxDurationInDays: BN;
  readonly coverExtendedClaimDurationInDays: BN;
};
export type AdminUpdateMetadataInfoAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly coverAdminAuth: PublicKey | string;
};
export type AdminEnlargeAccountParam = {
  readonly targetLength: BN;
};
export type AdminEnlargeAccountAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly coverAdminAuth: PublicKey | string;
  readonly rentPayer: PublicKey | string;
  readonly account: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
export type HandleNewCoverParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
  readonly coverOwner: PublicKey;
  readonly coverReferrer: PublicKey;
  readonly coverProductId: BN;
  readonly coverBeginTimestamp: BN;
  readonly coverEndTimestamp: BN;
  readonly coverCurrency: PublicKey;
  readonly coverAmount: BN;
  readonly coverOccupiedCommonAmount: BN;
  readonly coverOccupiedIndividualAmount: BN;
  readonly coverPremiumCurrency: PublicKey;
  readonly coverPremiumAmount: BN;
  readonly coverStatus: BN;
};
export type HandleNewCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly buyer: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
export type HandleRenewCoverParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
  readonly newCoverEndTimestamp: BN;
  readonly newCoverPremiumAmount: BN;
};
export type HandleRenewCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
};
export type HandleExpiredCoverParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
};
export type HandleExpiredCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
};
export type HandleCancelCoverParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
  readonly unearnedPremiumAmount: BN;
};
export type HandleCancelCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
};
export type HandleDispatchPremiumParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
  readonly dispatchedTimestamp: BN;
  readonly dispatchedPremiumAmount: BN;
};
export type HandleDispatchPremiumAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
};
export type HandleSubmitClaimParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
};
export type HandleSubmitClaimAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
};
export type HandleCloseClaimParam = {
  readonly callerIndex: BN;
  readonly coverId: BN;
  readonly claimedAmount: BN;
};
export type HandleCloseClaimAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly allowedCaller: PublicKey | string;
  readonly coverState: PublicKey | string;
};
