// Generated by "npm run codegen". Do not modify this file manually.
import type { BN } from '@project-serum/anchor';
import type { PublicKey } from '@solana/web3.js';

export type StakeToIndividualPoolParam = {
  readonly auwtAmount: BN;
};
export type StakeToIndividualPoolAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly individualPoolAuwtTokenAccount: PublicKey | string;
  readonly individualPoolLpAuwtMintAuthPda: PublicKey | string;
  readonly individualPoolLpAuwtMint: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly poolCpiAuthPda: PublicKey | string;
  readonly staker: PublicKey | string;
  readonly stakerState: PublicKey | string;
  readonly stakerAuwtAccount: PublicKey | string;
  readonly stakerLpAuwtAccount: PublicKey | string;
  readonly stakeReferrer: PublicKey | string;
  readonly sysvarRent: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly systemProgram: PublicKey | string;
  readonly tokenProgram: PublicKey | string;
  readonly auwtProgram: PublicKey | string;
};
export type UnstakeFromIndividualPoolParam = {
  readonly lpAuwtAmount: BN;
};
export type UnstakeFromIndividualPoolAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly poolAuwtAuthPda: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly individualPoolAuwtTokenAccount: PublicKey | string;
  readonly individualPoolLpAuwtMintAuthPda: PublicKey | string;
  readonly individualPoolLpAuwtMint: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly poolCpiAuthPda: PublicKey | string;
  readonly staker: PublicKey | string;
  readonly stakerState: PublicKey | string;
  readonly stakerLpAuwtBurnFromAccount: PublicKey | string;
  readonly stakerAuwtReceiverAccount: PublicKey | string;
  readonly sysvarRent: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly tokenProgram: PublicKey | string;
  readonly auwtProgram: PublicKey | string;
};
