// Generated by "npm run codegen". Do not modify this file manually.
import type { Idl, MethodsNamespace, Provider } from '@project-serum/anchor';
import type { PublicKey } from '@solana/web3.js';
import type { InstructionOption } from './Common';
import type * as entity from './PoolEntity';
import { Program } from '@project-serum/anchor';

type PoolMethodBuilders = {
  readonly stakeToIndividualPool: MethodsNamespace[keyof MethodsNamespace];
  readonly unstakeFromIndividualPool: MethodsNamespace[keyof MethodsNamespace];
};

export class PoolProgram {
  public readonly program: Program;

  public constructor(idl: Idl, address: PublicKey, provider: Provider) {
    this.program = new Program(idl, address, provider);
  }

  public get idl() {
    return this.program.idl;
  }

  public get programId() {
    return this.program.programId;
  }

  public get methods() {
    return this.program.methods as PoolMethodBuilders;
  }

  public stakeToIndividualPool(option: InstructionOption<entity.StakeToIndividualPoolParam, entity.StakeToIndividualPoolAccounts>) {
    return this.methods.stakeToIndividualPool(option.param.auwtAmount).accounts(option.accounts);
  }

  public unstakeFromIndividualPool(option: InstructionOption<entity.UnstakeFromIndividualPoolParam, entity.UnstakeFromIndividualPoolAccounts>) {
    return this.methods.unstakeFromIndividualPool(option.param.lpAuwtAmount).accounts(option.accounts);
  }

}
