// Generated by "npm run codegen". Do not modify this file manually.
import type { BN } from '@project-serum/anchor';
import type { PublicKey } from '@solana/web3.js';

export type QuotationResultState = {
  readonly premiumCurrency: PublicKey;
  readonly premiumAmount: BN;
  readonly creatorKey: PublicKey;
  readonly discountAmount: BN;
};
export type GetPremiumParam = {
  readonly productId: BN;
  readonly coverCurrency: PublicKey;
  readonly coverDurationInDays: BN;
  readonly coverAmount: BN;
};
export type GetPremiumAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly productState: PublicKey | string;
  readonly quotationState: PublicKey | string;
  readonly quotationResultState: PublicKey | string;
  readonly poolMetadataState: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly nftMetadataState: PublicKey | string;
};
