// Generated by "npm run codegen". Do not modify this file manually.
import type { BN } from '@project-serum/anchor';
import type { PublicKey } from '@solana/web3.js';

export type BuyCoverParam = {
  readonly coverId: BN;
  readonly coverOwner: PublicKey;
  readonly coverReferrer: PublicKey;
  readonly coverProductId: BN;
  readonly coverDurationInDays: BN;
  readonly coverCurrency: PublicKey;
  readonly coverAmount: BN;
};
export type BuyCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly premiumPoolAccountPda: PublicKey | string;
  readonly productState: PublicKey | string;
  readonly poolMetadataState: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly quotationMetadataState: PublicKey | string;
  readonly quotationState: PublicKey | string;
  readonly quotationResultState: PublicKey | string;
  readonly coverMetadataState: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly buyer: PublicKey | string;
  readonly nftAta: PublicKey | string;
  readonly nftMetadataState: PublicKey | string;
  readonly underwritingCallerAuthPda: PublicKey | string;
  readonly quotationProgram: PublicKey | string;
  readonly auwtProgram: PublicKey | string;
  readonly poolProgram: PublicKey | string;
  readonly coverProgram: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
export type RenewCoverParam = {
  readonly coverId: BN;
  readonly newCoverDurationInDays: BN;
};
export type RenewCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly premiumPoolAccountPda: PublicKey | string;
  readonly productState: PublicKey | string;
  readonly poolMetadataState: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly quotationMetadataState: PublicKey | string;
  readonly quotationState: PublicKey | string;
  readonly quotationResultState: PublicKey | string;
  readonly coverMetadataState: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly buyer: PublicKey | string;
  readonly nftAta: PublicKey | string;
  readonly nftMetadataState: PublicKey | string;
  readonly underwritingCallerAuthPda: PublicKey | string;
  readonly quotationProgram: PublicKey | string;
  readonly coverProgram: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
export type CancelCoverParam = {
  readonly coverId: BN;
};
export type CancelCoverAccounts = {
  readonly programMetadataState: PublicKey | string;
  readonly premiumPoolAccountPda: PublicKey | string;
  readonly treasurySolAccount: PublicKey | string;
  readonly poolMetadataState: PublicKey | string;
  readonly auwtState: PublicKey | string;
  readonly individualPoolState: PublicKey | string;
  readonly coverMetadataState: PublicKey | string;
  readonly coverState: PublicKey | string;
  readonly owner: PublicKey | string;
  readonly underwritingCallerAuthPda: PublicKey | string;
  readonly auwtProgram: PublicKey | string;
  readonly poolProgram: PublicKey | string;
  readonly coverProgram: PublicKey | string;
  readonly sysvarClock: PublicKey | string;
  readonly systemProgram: PublicKey | string;
};
